### ISSUE TITLE
Search points by envelope/polygon?

### ISSUE THREAD

**Issue by bertt** [shintadono/laszip.net#11]
Hi, Is there a possibility to search points in the las file by footprint envelope and/or polygon? Or do I have to loop through all points and figure it out myself.

**Comment by rapidlasso** [comment]
The original LASzip API has a function to limit the points to a rectangle. If spatially indexed with lasindex (LAX file are present) such an area-of-interest query can then be significantly faster as only a small subset of relevant points needs to be decompressed (assuming some spatially coherent order of points in the file). It seems this function was not translated to this API:

https://github.com/LASzip/LASzip/blob/master/include/laszip/laszip_api.h#L531

**Comment by bertt** [comment]
ok thanks for the clarification!
