### ISSUE TITLE
Setting number of points count in header

### ISSUE THREAD

**Issue by erdogdum** [shintadono/laszip.net#12]
Hi,

Nice framework for reading/writing laz files. Thanks for your efforts.

I am directly reading point data from a source which i can not guess the total number of points before writing them to laz file.

Thats why i can not set the "header.number_of_point_records" before writing points.
When i try to set it right before closing the writer after finishing my point iteration, it does not take it in account and the result file's header is not be updated.

Do you have any suggestion in order to update "header.number_of_point_records" after opening the writer ?

**Comment by rapidlasso** [comment]
The original C/C++ DLL does update the counters on close. Or at least there is an "update inventory" function that can be called after each written point so that also the return number histogram and the bounding box is logged as the points are written, Was that functionality not ported to C#?

**Comment by twdotson** [comment]
Yes, the update_inventory appears to be ported and appears to work.  As you mention it must be called after each written point.

**Comment by fnvespucci** [comment]
Hi,

I'm having the same issue.
There is some guide to the library, or some document of sort for the correct way to use it?

What I'm trying to do is change the classification of some points, given a criteria.
For what I understood I cannot simply change the values, but write a new file in output, right?

So I "clone" the header from a reader of the original file (extent of the data, offset, scale factor, format, record length and the vlr) and then while reading I write in the writer the input point, in the following way (vb.net, using the develop branch of the library):

`lasR.read_point()`
`lasW.set_point(lasR.point)`
`lasW.write_point()`

Actually I'm not changing anything on the single point.
But at the end, using the lasinfo tool, i have the following result:

`reporting minimum and maximum for all LAS point record entries ...`
`  X                   0          0`
`  Y                   0          0`
`  Z                   0          0`
`  intensity           0          0`
`  return_number       1          1`
`  number_of_returns   1          1`
`  edge_of_flight_line 0          0`
`  scan_direction_flag 0          0`
`  classification      0          0`
`  scan_angle_rank     0          0`
`  user_data           0          0`
`  point_source_ID     0          0`
`  gps_time 0.000000 0.000000`
`  Color R 0 0`
`        G 0 0`
`        B 0 0`
`number of first returns:        0`
`number of intermediate returns: 0`
`number of last returns:         0`
`number of single returns:       0`
`WARNING: real min x smaller than header min x by 7207000.000000`
`WARNING: real min y smaller than header min y by 4557000.000000`
`WARNING: real min z smaller than header min z by 15.060000`

If I set the `number_of_point_records` in the header the result change giving as warning about the number of points by return:

`reporting minimum and maximum for all LAS point record entries ...`
`  X           720700000  720749999`
`  Y           455700000  455749999`
`  Z                1506      18675`
`  intensity           1       5583`
`  return_number       1          5`
`  number_of_returns   1          5`
`  edge_of_flight_line 0          0`
`  scan_direction_flag 0          0`
`  classification      1          7`
`  scan_angle_rank   -30         30`
`  user_data           0          0`
`  point_source_ID    28         33`
`  gps_time 291632.812352 293422.399562`
`  Color R 0 0`
`        G 0 0`
`        B 0 0`
`number of first returns:        2298775`
`number of intermediate returns: 8747`
`number of last returns:         2299208`
`number of single returns:       2038405`
`WARNING: for return 1 real number of points by return is 2298775 but header entry was not set.`
`WARNING: for return 2 real number of points by return is 260785 but header entry was not set.`
`WARNING: for return 3 real number of points by return is 8565 but header entry was not set.`
`WARNING: for return 4 real number of points by return is 197 but header entry was not set.`
`WARNING: for return 5 real number of points by return is 3 but header entry was not set.`
`overview over number of returns of given pulse: 2038405 504069 25065 771 15 0 0`
`histogram of classification of points:`
`         1008509  unclassified (1)`
`          482887  ground (2)`
`          671834  low vegetation (3)`
`          374173  medium vegetation (4)`
`           28432  high vegetation (5)`
`            2424  building (6)`
`              66  noise (7)`

What is the correct way to manage this kind of processing?

TIA

**Comment by fnvespucci** [comment]
Nevermind.

I found the `update_inventory` and as suggested now I'm forcing it after every `write_point`.
It update, as expected, the extent, number of points and number of points by return.

In any case, could be very useful a manual or something similar for the library.

Sorry for annoying, and thanks for the good job you are doing

Regards
