### ISSUE TITLE
Set number_of_extended_variable_length_records and info of spatial references

### ISSUE THREAD

**Issue by lorusso86** [shintadono/laszip.net#13]
Hi, i have created a file Las from X,Y,Z points and it work.
Now i wont set the info of spatial reference (latitude, longitude etc..).
I have seen from specific of las files and i read that is important set the "number_of_extended_variable_length_records".
I dont understand how set all other information  (latitude, longitude etc..).
can someone help me to set this information?? also an example is good.
Thx

**Comment by shintadono** [comment]
laszip.net is a (rather old) C++ port of [LASZip](https://github.com/LASzip/LASzip). I tried to keep the API the same, so any example in C/C++ would be easy to convert to C++. For general questions about how to use LASZip and laszip.net please refer to that repository, or try the [lasroom forum](https://groups.google.com/g/lasroom).
