### ISSUE TITLE
Get number of classifications

### ISSUE THREAD

**Issue by heatgithub** [shintadono/laszip.net#14]
I would like to read the number of classifications in a LAS file without have to go through all the points. And even better, also get what classifications it is. Maybe it is already possible but I haven't found out how to do it?
If running LASinfo from LASTools, at the end you see something like this, there max classification is and at last, a list of the classifications in the file.

reporting minimum and maximum for all LAS point record entries ...
  X            -5666700   -5593800
  Y             4825300    4870600
  Z               18593      23050
  intensity           2        241
  return_number       1          4
  number_of_returns   1          4
  edge_of_flight_line 0          1
  scan_direction_flag 0          1
  classification      1         11
  scan_angle_rank   -15         23
  user_data           0          0
  point_source_ID 19904      19905
  gps_time 128993.662014 164619.556113
overview over number of returns of given pulse: 391697 33254 4442 145 0 0 0
histogram of classification of points:
          143525  unclassified (1)
          285623  ground (2)
             390  road surface (11)

**Comment by rapidlasso** [comment]
This is maybe the wrong forum to ask this. It is in general not possible to get the classification histogram without parsing all the points.

**Comment by heatgithub** [comment]
Yes I know it's not really an issue, but I didn't see any better place to ask the question.
Thanks for the answer, I solve it with parsing the points.

**Comment by rapidlasso** [comment]
The [LAStools user forum](https://groups.google.com/d/forum/lastools) is a good place for such inquiries.
