### ISSUE TITLE
write las

### ISSUE THREAD

**Issue by lazicsasalaki** [shintadono/laszip.net#21]
When I use the 'write las' class, I would like to write values for min and max intensity as follows:

intensity 0 65535

How can I do that? Is there a way to accomplish this?

thanks

**Comment by shintadono** [comment]
laszip.net is a (rather old) C++ port of [LASZip](https://github.com/LASzip/LASzip). I tried to keep the API the same, so any example in C/C++ would be easy to convert to C++. For general questions about how to use LASZip and laszip.net please refer to that repository, or try the [lasroom forum](https://groups.google.com/g/lasroom).
