### ISSUE TITLE
Support for POINT14 and RGBNIR14 from LAZ files

### ISSUE THREAD

**Issue by ahuarte47** [shintadono/laszip.net#6]
Hi @shintadono, first of all thank you very much for this great library.

I have a question about this, are there any plans to support POINT14 and RGBNIR14 items from compressed LAZ files (v1.4).

Thanks in advance

**Comment by shintadono** [comment]
Hi there,

I guess I totally missing the announcement of native LAZ 1.4 support for the original laszip being finished. I thought it is still in development and still only available as prototype release.

I can't make any promisses on a release date, but there will be release, that includes the new native compression for LAS 1.4. I don't know, if there will be support for the 'compatibility mode', though.

**Comment by ahuarte47** [comment]
Thanks @shintadono for the response!. [laszip](https://github.com/LASzip/LASzip) already reads LAZ files with **compression v3**. ok, I am using it for my own LAZ files.

**Comment by rapidlasso** [comment]
We've made native LASzip compression for "LAS 1.4" so far only a quiet "soft release" to see whether there are any kinks left. The official announcement will come soon. In theory all should be ready and all LAStools have it already integrated. Just switching out the LASzip.dll for other software seems to work just fine but I only tried it with FUSION so far.

**Comment by hobu** [comment]
> We've made native LASzip compression for "LAS 1.4" so far only a quiet "soft release" to see whether there are any kinks left. 

Yes, this  is the current situation. We have also been testing PDAL with LAZ 1.4 as part of the recent PDAL 1.6.0 release, and it has been working well in testing.

**Comment by ahuarte47** [comment]
Thanks everyone for your work!
